---
title: "Problem set 8"
date: "2025-05-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
```

## Instructions

Please use an RMarkdown file to complete this assignment. Make sure you reserve code chunks for code and write out any interpretations or explainations outside of code chunks. Submit the knitted PDF file containing your code and written answers on Canvas. 

## Questions

1. The data in `data(Oxboys, package="rethinking")` is 234 height measurements on 26 boys from an Oxford Boys Club, at 9 different ages (centered and standardized) per boy. Predict height, using age, clustered by `Subject` (individual boy). Fit a model with varying intercepts and slopes (on `age`), clustered by `Subject.` Present and interpret the parameter estimates. Which varying effect contributes more variation to the heights, the intercept or the slope?

2. Now consider the correlation between the varying intercepts and slopes. Can you explain its value? How would this estimated correlation influence your predictions about a new sample of boys?
