---
title: "Problem set 9"
date: "2025-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
```

## Instructions

Please use an RMarkdown file to complete this assignment. Make sure you reserve code chunks for code and write out any interpretations or explainations outside of code chunks. Submit the knitted PDF file containing your code and written answers on Canvas. 

## Questions

1. For this question, use the data from the study of political attitudes discussed in class. [Download the csv file here](https://osf.io/782ez). You can see the description of the data [here](https://openpsychologydata.metajnl.com/articles/10.5334/jopd.54#3-dataset-description)). Consider the question about healthcare (`health`): Should federal spending on healthcare be increased, decreased, or kept the same?. Model reponses to this variable as a function of wave, using a Gaussian process. Remember that you'll need to clean the data first. Plot the expected response as a function of wave. 

2. Categorize each participant as either "young" or "old" using whatever cut-off you want for old (but being sensitive to the feelings of your instructor). Incorporate this variable into your model. How does it change your interpretation of the findings? (An important note: age is only assessed at baseline.)


