---
title: "Problem set 10"
date: "2025-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
```

## Instructions

Please use an RMarkdown file to complete this assignment. Make sure you reserve code chunks for code and write out any interpretations or explanations outside of code chunks. Submit the knitted PDF file containing your code and written answers on Canvas.

## Questions

You have a choice this week. You can either:

1.  Redo one of the earlier problem sets from this term. Pick an assignment that you struggled with or didn't feel like you understood well. Answer the questions from the assignment and consider doing a little more: ask an additional research question, integrate a technique from a different part of the course, or make a publication-worthy figure. Do not copy the answer key and don't use generative AI. Instead, refer to slides and notes and help pages for `brms`. This is an opportunity to master a skill.

2.  Analyze your own data. You should include the following:

    1.  A written statement of the research question

    2.  A causal model (DAG)

    3.  A generative simulation

    4.  The statistical model

    5.  A figure of the posterior distribution and a figure of the posterior predictive distribution