---
title: "Readings, lectures, and videos"
---

Each class session has one or two videos that you should watch ***before*** coming to class. These videos are the lectures recorded by Richard McElreath.

The in-class lecture slides are special HTML files made with the R package [**xaringan**](https://bookdown.org/yihui/rmarkdown/xaringan.html) (R can do so much!). On each class session page you'll see buttons for opening the presentation in a new tab or for downloading a PDF of the slides in case you want to print them or store them on your computer:

<p class="buttons" style="text-align:center;"><span class="btn btn-danger">{{< fa arrow-up-right-from-square >}} View all slides in new window</span> <span class="btn btn-danger">{{< fa file-pdf >}} Download PDF of all slides</span></p>

The slides are also embedded on each page. You can click in the slides and navigate through them with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while viewing the slides you can see a list of slide-specific commands (like <kbd>f</kbd> for fullscreen or <kbd>p</kbd> for presenter mode if you want to see my notes).

I will note for each set of lecture slides which chapters in the 2nd edition of the McElreath book correspond with that day's lesson. However, many of the functions we use -- especially starting in week 4 -- will not be from McElreath's materials, but instead from the `brms` and `tidybayes` packages.
